//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieNight
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieNightDBEntities3 : DbContext
    {
        public MovieNightDBEntities3()
            : base("name=MovieNightDBEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MovieTable> MovieTable { get; set; }
        public virtual DbSet<PictureTable> PictureTable { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
    }
}
