//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieNight
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieTable()
        {
            this.PictureTable = new HashSet<PictureTable>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Year { get; set; }
        public string Genre { get; set; }
        public string Sound { get; set; }
        public string Quality { get; set; }
        public string Description { get; set; }
        public string Length { get; set; }
        public string Director { get; set; }
        public string Cast { get; set; }
        public string Raiting { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PictureTable> PictureTable { get; set; }
    }
}
