//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieNight
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class PictureTable
    {
        public int Id { get; set; }
        public string Background_Big { get; set; }
        public string Background_Smal { get; set; }
        public int FilmId { get; set; }
        public string YoutubeLink { get; set; }
    
        public virtual MovieTable MovieTable { get; set; }

        public HttpPostedFileBase thePicture { get; set; }  //för att kunna ladda upp filer. https://www.youtube.com/watch?v=5L5W-AE-sEs&feature=youtu.be&fbclid=IwAR3mzc9FTcpRnx1hNCUL_n_MibWT0tIcQyYTMWBtkO9DA9-9pcW61HdxIic
        public HttpPostedFileBase thePicture2 { get; set; }
    }
}
